import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Toast from './(__secure__)/components/Toast'
import TopNav from './(__secure__)/components/TopNav'
import WelcomeUser from './client/components/WelcomeUser'
import { cookies } from "next/headers";
import ReactQueryClientProvider from './(__pages__)/providers/ReactQueryClientProvider'
import CardPage from './modals/card/CardPage'
import {CardBeingViewedContextProvider} from './(__pages__)/context/CardBeingViewedContext'
import { ToggleMenuContextProvider } from './(__pages__)/context/ToggleMenuContext'
import Menu from './modals/Menu'
import { ToggleSearchContextProvider } from './(__pages__)/context/ToggleSearchContext'
import Search from './modals/search/Search'
import { MoviesOrTVshowsLinksContextProvider } from './(__pages__)/context/MoviesOrTVshowsLinksContext'
import { MoviesOrTVshowsInfoContextProvider } from './(__pages__)/context/MoviesOrTVshowsInfoContext'
import { ThemeContextProvider } from './(__pages__)/context/ThemeContext'
import { ImagesAndVideosContextProvider } from './(__pages__)/context/ImagesAndVideosContext'
import AllImages from './modals/all-images-and-videos/AllImages'
import {ToggleShowPersonContextProvider } from './(__pages__)/context/ToggleShowPersonContext'
import Person from './modals/card/components/person/Person'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Moviies and TVshows information app',
  description: 'Generated by create next app',
}




export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cookieStore = cookies();
  const isGuess = cookieStore.get('TMDB_guest_session_id')?.value
  
  return (
    <html lang="en">
        <body className={`${inter.className} relative`}>
          <ReactQueryClientProvider>
            <MoviesOrTVshowsLinksContextProvider>
              <MoviesOrTVshowsInfoContextProvider>
                <CardBeingViewedContextProvider>
                  <ToggleMenuContextProvider>
                    <ToggleSearchContextProvider>
                      <ThemeContextProvider>

                        <>{/* <TopNav /> */}</>
                        <main >
                          {children}
                          {!isGuess && <WelcomeUser /> }
                          <Toast />

                          <canvas id="canvas"></canvas>
                        </main>

                        <ToggleShowPersonContextProvider>
                          {/* <Menu /> */}
                          <Search />
                          <CardPage />
                          <Person />
                          {/* <AllImages /> */}
                        </ToggleShowPersonContextProvider>

                      </ThemeContextProvider>
                    </ToggleSearchContextProvider>
                  </ToggleMenuContextProvider>
                </CardBeingViewedContextProvider>
              </MoviesOrTVshowsInfoContextProvider>
            </MoviesOrTVshowsLinksContextProvider>
          </ReactQueryClientProvider>
        </body>
    </html>
  )
}
