import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Toast from './(__secure__)/components/Toast'
import TopNav from './(__secure__)/components/TopNav'
import WelcomeUser from './client/components/WelcomeUser'
import { cookies } from "next/headers";
import ReactQueryClientProvider from './(__pages__)/providers/ReactQueryClientProvider'
import Search from './(__pages__)/search/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cookieStore = cookies();
  const isGuess = cookieStore.get('TMDB_guest_session_id')?.value
  
  return (
    <html lang="en">
        <body className={`${inter.className}`}>
          <ReactQueryClientProvider>
            <>{/* <TopNav /> */}</>
            <main >
              {children}
              {!isGuess && <WelcomeUser /> }
              <Toast />
            </main>
          </ReactQueryClientProvider>
        </body>
    </html>
  )
}
